#!/usr/bin/env python3
"""
Publish simulation reports to docs/reports/{project}/ for GitHub Pages.

Copies selected report files from output directories (output_simulation/,
output_exploration/, output_view/) to docs/reports/{project}/.
index.html is auto-generated by GitHub Actions on push.

Usage:
    python publish_report.py                                # publish all from output_*
    python publish_report.py --filter "20260218-014100"     # publish specific run
    python publish_report.py --source output_simulation     # from specific dir
    python publish_report.py --dry-run                      # preview only
    python publish_report.py --local-index                  # also generate index locally
"""

import argparse
import os
import re
import shutil
import subprocess
import sys

# Report file pattern: {project}-{scenario}-{YYYYMMDD-HHMMSS}-{writer}_suffix.ext
REPORT_PATTERN = re.compile(
    r'^(?P<project>[^-]+)-(?P<scenario>.+?)'
    r'-(?P<timestamp>\d{8}-\d{6})'
    r'-(?P<writer>[^_]+)_'
)

# Output directories to scan (in order)
DEFAULT_SOURCE_DIRS = ['output_simulation', 'output_exploration', 'output_view']

# File extensions to publish
PUBLISH_EXTENSIONS = {'.html', '.md', '.png', '.csv', '.json'}


def find_report_files(source_dirs: list, filter_str: str = None) -> list:
    """Find report files matching the naming convention."""
    files = []
    for src_dir in source_dirs:
        if not os.path.isdir(src_dir):
            continue
        for filename in os.listdir(src_dir):
            filepath = os.path.join(src_dir, filename)
            if not os.path.isfile(filepath):
                continue
            _, ext = os.path.splitext(filename)
            if ext.lower() not in PUBLISH_EXTENSIONS:
                continue
            m = REPORT_PATTERN.match(filename)
            if not m:
                continue
            if filter_str and filter_str not in filename:
                continue
            files.append({
                'source': filepath,
                'filename': filename,
                'project': m.group('project'),
            })
    return files


def publish_files(files: list, dest_base: str, dry_run: bool = False) -> list:
    """Copy files to docs/reports/{project}/."""
    published = []
    for f in files:
        dest_dir = os.path.join(dest_base, f['project'])
        dest_path = os.path.join(dest_dir, f['filename'])
        
        if dry_run:
            print(f"  [DRY-RUN] {f['source']} → {dest_path}")
        else:
            os.makedirs(dest_dir, exist_ok=True)
            shutil.copy2(f['source'], dest_path)
            print(f"  ✓ {f['filename']} → {dest_dir}/")
        published.append(dest_path)
    return published


def main():
    parser = argparse.ArgumentParser(
        description='Publish simulation reports to docs/reports/ for GitHub Pages'
    )
    parser.add_argument(
        '--source', '-s', nargs='+', default=None,
        help=f'Source directories (default: {", ".join(DEFAULT_SOURCE_DIRS)})'
    )
    parser.add_argument(
        '--dest', '-d', default='docs/reports',
        help='Destination reports directory (default: docs/reports)'
    )
    parser.add_argument(
        '--filter', '-f', default=None,
        help='Filter: only publish files containing this string (e.g., timestamp or writer)'
    )
    parser.add_argument(
        '--dry-run', action='store_true',
        help='Preview files to publish without copying'
    )
    parser.add_argument(
        '--local-index', action='store_true',
        help='Also regenerate index.html locally (default: let GitHub Action handle it)'
    )
    args = parser.parse_args()
    
    source_dirs = args.source or DEFAULT_SOURCE_DIRS
    
    print(f"Scanning source directories: {', '.join(source_dirs)}")
    if args.filter:
        print(f"Filter: '{args.filter}'")
    
    files = find_report_files(source_dirs, args.filter)
    
    if not files:
        print("\nNo matching report files found.")
        print("Tip: Run simulation first to generate reports with the new naming format.")
        return
    
    print(f"\nFound {len(files)} file(s) to publish:")
    published = publish_files(files, args.dest, dry_run=args.dry_run)
    
    # Optionally regenerate index.html locally
    if not args.dry_run and args.local_index:
        print("\nRegenerating index.html locally...")
        script_dir = os.path.dirname(os.path.abspath(__file__))
        index_script = os.path.join(script_dir, 'generate_index.py')
        if os.path.exists(index_script):
            subprocess.run([
                sys.executable, index_script,
                '--reports-dir', args.dest,
                '--output', os.path.join(os.path.dirname(args.dest), 'index.html'),
            ], check=True)
        else:
            print(f"  [Warning] generate_index.py not found at {index_script}")
    
    if not args.dry_run:
        print(f"\n✅ Published {len(published)} file(s) to {args.dest}/")
        print("\nNext steps:")
        print("  git add docs/reports/")
        print("  git commit -m \"Add simulation reports\"")
        print("  git push")
        print("\n  → GitHub Action will auto-generate index.html and deploy to Pages")


if __name__ == '__main__':
    main()

